application:
  name: people-manager
spring:
  application:
    name=${application.name}:
  data:
    mongodb:
      uri: mongodb://localhost:27017/peoplemanager
      auto-index-creation: true
#  datasource:
#    url: jdbc:h2:mem:peoplemanager
#    username: root
#    password: root
#    driverClassName: org.h2.Driver
#    jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#      hibernate:
#        ddl-auto: update
#        globally_quoted_identifiers: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
peoplemanager:
  jwt:
    secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
    expiration: 86400000